algoritmo "Exercicio 28"
//Faca a leitura de tres valores e apresente como resultado a soma dos quadrados dos tres valores lidos
var
v1:inteiro
v2:inteiro
v3:inteiro
soma:real
inicio
      escreva("Digite o primeiro valor: ")
      leia(v1)
      escreva("Digite o segundo valor: ")
      leia(v2)
      escreva("Digite o terceiro valor: ")
      leia(v3)
      soma <- (v1 ^ 2) + (v2 ^ 2) + (v3 ^ 2)
      escreva("O valor das somas dos tres valores eh:",soma)
fimalgoritmo
