algoritmo "exercicio 29"
//Leia quatro notas, calcule a media aritm ´ etica e imprima o resultado
var
   n1, n2, n3, n4:inteiro
   m:real
inicio
      escreva("Digite uma nota: ")
      leia(n1)
      escreva("Digite a segunda nota: ")
      leia(n2)
      escreva("Digite a terceira nota: ")
      leia(n3)
      escreva("Digite a Quarta nota: ")
      leia(n4)
      m <- (n1 + n2 + n3 + n4)/4
      escreva("A media das Quatros notas eh:",m)
fimalgoritmo
